# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CabuChatApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CabuChatApp

	pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
  	pod 'JSQMessagesViewController'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'

  target 'CabuChatAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CabuChatAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
